<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpqmqr2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpqmqr2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZpqmqr2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZpqmqr2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZpqmqr2\appProdProjectContainer(array(
    'container.build_hash' => 'Zpqmqr2',
    'container.build_id' => '630eeae2',
    'container.build_time' => 1543203909,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpqmqr2');
