<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqyhlsw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqyhlsw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXqyhlsw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXqyhlsw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXqyhlsw\appProdProjectContainer(array(
    'container.build_hash' => 'Xqyhlsw',
    'container.build_id' => 'ca998ff7',
    'container.build_time' => 1544500535,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqyhlsw');
