<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0tdvove\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0tdvove/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0tdvove.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0tdvove\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0tdvove\appProdProjectContainer(array(
    'container.build_hash' => '0tdvove',
    'container.build_id' => '24a50627',
    'container.build_time' => 1549425788,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0tdvove');
